### ISSUE TITLE
editor glitch

### ISSUE THREAD

**Issue by ihateworkthatshard** [TheTastyPi/just-a-platformer#41]
umm... I was working on a level when the controls stopped working I've tried to reload but nothing is working

**Comment by ihateworkthatshard** [comment]
here is the level btw: [[[1,0,0,0,0,14,0,3,0,0,0,0,24,[46,"HARD"],[46,"Text"],[84,1,0],1,0,2,11,2,11,1,1,[17,325,20,600,[null,null,false],false,false,false,4000,20,1,false,0,[]],[73,1,0,1,0],0,3],[1,0,0,0,1,0,0,0,0,0,0,0,40,[46,"Text"],[46,"Text"],[84,1,0],[84,1,0],1,0,0,3,7,1,9,7,[73,1,0,1,0],0,0],[1,0,0,0,2,1,0,0,0,0,0,2,40,[46,"Text"],[46,"Text"],[84,1,0],[84,1,0],1,0,2,11,0,0,0,2,[73,1,0,1,60],[73,0,0,60,60],[73,0,[49,20],60,60]],[1,0,0,[34,1],[31,1,false,"unused"],1,0,[84,1,0],[84,1,0],[84,1,0],[84,1,0],2,40,[46,"Text"],[46,"Text"],[84,1,0],1,0,0,0,22,1,0,0,1,[73,1,0,1,0],0,0],[1,0,0,2,[34,1],1,0,[74,255,127,127],[73,[84,1,0],[84,1,0],[74,255,127,127],[84,1,0]],[73,[84,1,0],0,0,0],0,2,40,0,0,0,6,1,0,0,1,0,0,0,2,[73,1,0,1,0],0,0],[1,0,0,2,2,1,0,[74,255,127,127],[73,[74,255,127,127],[84,1,0],[84,1,0],[84,1,0]],[73,0,0,[84,1,0],0],0,2,40,0,1,0,3,1,3,16,1,0,0,0,1,[73,1,0,1,0],0,0],[1,0,0,2,2,1,0,[84,1,0],[84,1,0],[84,1,0],[84,1,0],2,40,0,1,0,0,1,0,0,2,0,0,0,2,[73,1,0,1,0],0,0],[1,0,0,0,2,1,0,0,0,0,0,2,40,0,[84,1,0],0,2,1,0,2,2,0,0,0,1,[73,1,2,1,0],[73,2,2,0,0],[73,0,2,0,0]],[1,0,0,0,0,1,0,[73,0,0,0,[84,1,0]],[84,1,0],[84,1,0],[84,1,0],2,40,0,[84,1,0],0,8,1,7,60,2,0,0,0,2,[73,1,0,1,0],0,0],[1,0,0,0,0,1,0,[84,1,0],[73,[84,1,0],[74,255,127,127],[84,1,0],[74,255,127,127]],[73,[74,255,127,127],[84,1,0],[74,255,127,127],[84,1,0]],[73,[84,1,0],0,[84,1,0],0],2,40,0,1,8,8,2,0,0,2,0,0,[84,1,0],3,[73,1,0,1,0],0,0],[1,1,0,0,0,1,0,[73,0,[84,1,0],0,0],[84,1,0],[84,1,0],[84,1,0],2,40,0,2,0,13,[84,1,0],0,0,5,59,0,0,6,[73,1,0,1,0],0,0],[1,1,1,0,0,1,0,0,0,0,0,2,40,0,1,7,3,1,1,7,1,1,1,1,1,[73,1,0,1,0],0,0],[1,1,1,0,[50,2000],1,0,[84,1,0],[84,1,0],[84,1,0],[84,1,0],2,40,0,1,1,1,1,1,1,1,2,2,[84,1,0],2,[73,1,0,1,0],0,0],[1,1,1,0,2,1,0,[84,1,0],[74,255,127,127],[84,1,0],[73,0,0,[84,1,0],0],2,40,0,0,11,2,11,1,1,2,[84,1,0],2,2,[84,1,0],[73,1,2,1,0],[73,0,2,0,0],[73,2,2,0,0]],[1,1,1,0,0,1,0,[73,0,[84,1,0],0,0],[84,1,0],[73,[84,1,0],[84,1,0],0,0],[84,1,0],2,40,9,0,0,0,0,0,0,2,2,2,2,[84,1,0],[73,1,0,1,0],0,0],[1,1,1,0,0,1,0,0,0,0,0,0,5,11,11,2,11,2,0,0,2,[84,1,0],2,2,[84,1,0],[73,1,0,1,0],0,0],[[51,127,127,255],[51,127,127,255],[51,127,127,255],[51,127,127,255],0,1,0,[84,1,0],[84,1,0],[84,1,0],[84,1,0],2,40,3,0,60,2,0,0,0,2,2,2,[84,1,0],2,[73,1,0,1,0],0,0],[[73,[51,127,127,255],1,[51,127,127,255],1],[73,[51,127,127,255],[51,127,127,255],1,1],[73,[51,127,127,255],[51,127,127,255],1,1],[51,127,127,255],0,1,0,[84,1,0],[73,[74,255,127,127],[74,255,127,127],[84,1,0],[74,255,127,127]],[73,[74,255,127,127],[74,255,127,127],[74,255,127,127],[84,1,0]],[84,1,0],2,40,62,0,0,0,0,0,2,11,2,0,0,0,[73,1,0,1,0],0,0],[[73,[51,127,127,255],1,[51,127,127,255],[51,127,127,255]],[51,127,127,255],[51,127,127,255],[51,127,127,255],0,1,0,[73,0,[84,1,0],0,0],[84,1,0],[84,1,0],[73,[84,1,0],0,0,0],2,40,[84,1,0],1,[84,1,0],2,2,0,0,0,0,25,0,0,[73,1,0,1,0],0,0],[[73,[51,127,127,255],1,[51,127,127,255],[51,127,127,255]],[73,1,1,[51,127,127,255],[51,127,127,255]],[73,1,1,1,[51,127,127,255]],[51,127,127,255],0,1,0,0,0,0,0,2,40,0,0,0,2,0,0,11,1,3,1,0,16,[73,1,0,1,2],[73,0,0,2,2],[73,0,0,2,0]],[[73,[51,127,127,255],1,[51,127,127,255],[51,127,127,255]],[73,1,1,[51,127,127,255],[51,127,127,255]],[73,1,1,[51,127,127,255],[51,127,127,255]],[51,127,127,255],0,1,0,[84,1,0],[84,1,0],[84,1,0],[84,1,0],2,40,7,0,59,2,0,0,26,0,12,25,0,0,[73,1,0,1,0],0,0],[[73,[51,127,127,255],1,[51,127,127,255],1],[73,1,1,[51,127,127,255],1],[73,1,1,[51,127,127,255],1],[51,127,127,255],0,1,0,[73,[74,255,127,127],[84,1,0],[74,255,127,127],[74,255,127,127]],[84,1,0],[73,0,0,[84,1,0],0],0,2,40,0,0,0,0,3,1,2,0,0,0,25,0,[73,1,0,1,0],0,0],[[51,127,127,255],[51,127,127,255],[51,127,127,255],[51,127,127,255],0,1,0,[74,255,127,127],[73,[74,255,127,127],[84,1,0],[74,255,127,127],[84,1,0]],[84,1,0],0,0,40,1,0,0,0,0,0,26,0,0,0,2,0,[73,1,0,1,0],0,0],[[73,[51,127,127,255],1,[51,127,127,255],1],[73,1,1,[51,127,127,255],1],[73,1,1,[51,127,127,255],1],[51,127,127,255],0,1,0,[73,[74,255,127,127],[74,255,127,127],[74,255,127,127],[84,1,0]],[84,1,0],[73,[84,1,0],0,0,0],0,2,40,0,1,1,1,1,1,1,2,0,3,1,0,[73,1,0,1,0],0,0],[[73,[51,127,127,255],[51,127,127,255],[51,127,127,255],1],[73,[51,127,127,255],[51,127,127,255],1,1],[73,[51,127,127,255],[51,127,127,255],1,1],[51,127,127,255],0,1,0,[84,1,0],[84,1,0],[84,1,0],[84,1,0],2,40,0,0,0,0,0,0,0,0,0,0,24,0,[73,1,0,1,0],0,0],[[51,127,127,255],[73,1,[51,127,127,255],[51,127,127,255],1],[51,127,127,255],[51,127,127,255],0,1,0,0,0,0,0,2,40,13,2,2,2,2,2,2,2,2,2,2,2,[73,1,0,1,0],0,0],[[73,[51,127,127,255],1,[51,127,127,255],1],1,1,[51,127,127,255],23,1,0,[73,0,0,0,[84,1,0]],[84,1,0],[84,1,0],[73,0,0,[84,1,0],0],2,40,3,0,0,25,2,1,16,0,7,13,0,3,[73,1,0,1,0],0,0],[[73,[51,127,127,255],1,[51,127,127,255],[51,127,127,255]],[73,[51,127,127,255],[51,127,127,255],1,1],[73,[51,127,127,255],1,1,[51,127,127,255]],[51,127,127,255],56,1,0,[84,1,0],[73,[84,1,0],[74,255,127,127],[84,1,0],[74,255,127,127]],[73,[74,255,127,127],[84,1,0],[74,255,127,127],[84,1,0]],[84,1,0],2,40,26,0,0,0,2,1,26,0,0,25,0,60,[73,1,0,1,0],0,0],[[51,127,127,255],[73,[51,127,127,255],[51,127,127,255],1,[51,127,127,255]],[51,127,127,255],[51,127,127,255],3,1,0,[73,0,[84,1,0],0,0],[84,1,0],[84,1,0],[73,[84,1,0],0,0,0],0,40,2,0,0,0,25,1,2,0,0,2,0,0,[73,1,0,1,2],[73,0,0,2,0],[73,0,0,2,2]],[[73,[51,127,127,255],1,[51,127,127,255],1],[73,[51,127,127,255],[51,127,127,255],[51,127,127,255],1],[73,1,1,[51,127,127,255],[51,127,127,255]],[73,[51,127,127,255],1,[51,127,127,255],[51,127,127,255]],60,1,0,0,0,0,0,2,40,26,0,0,0,2,1,0,0,0,2,0,11,[73,1,0,1,0],0,0],[[51,127,127,255],[73,1,[51,127,127,255],[51,127,127,255],[51,127,127,255]],[51,127,127,255],[51,127,127,255],60,1,0,[84,1,0],[84,1,0],[84,1,0],[84,1,0],2,40,2,0,0,0,25,1,0,0,2,2,0,0,[73,1,0,1,0],0,0],[2,62,11,62,7,1,0,[84,1,0],[74,255,127,127],[74,255,127,127],[84,1,0],2,40,26,0,0,0,0,0,0,3,16,1,0,6,[73,1,0,1,0],0,[73,0,0,0,2]],[0,0,[27,100],[29,100],0,1,0,[73,0,[84,1,0],0,0],[84,1,0],[84,1,0],[73,[84,1,0],0,0,0],2,40,2,2,2,2,2,2,1,1,1,1,1,3,[73,1,2,1,0],0,0],[2,0,0,0,0,5,0,0,0,0,0,2,40,2,0,0,0,0,2,0,0,2,11,2,7,[73,1,0,1,0],0,0],[2,0,2,2,61,1,0,[73,1,[84,1,0],1,[84,1,0]],[84,1,0],[84,1,0],[84,1,0],0,40,2,2,2,2,0,2,0,0,0,0,0,23,[73,1,0,1,0],0,[73,0,0,0,2]],[0,7,40,0,0,[73,[30,100],[30,100],2,2],[73,60,60,0,0],[73,1,[74,255,127,127],1,[74,255,127,127]],[84,1,0],[74,255,127,127],[84,1,0],0,40,2,2,2,2,2,2,0,0,0,0,0,0,[73,1,0,1,0],0,0],[0,8,40,0,2,1,0,0,0,0,0,8,40,2,0,0,0,0,0,0,0,0,0,0,0,[73,1,0,1,0],0,[73,0,0,2,0]],[0,2,40,0,[73,1,1,0,0],1,0,0,0,0,8,7,[29,100],[33,0],0,6,0,0,0,0,0,0,0,0,0,[73,1,2,1,0],0,0],[0,3,40,0,0,[73,1,1,2,2],0,0,0,0,0,3,[29,100],2,0,0,[29,100],11,[31,0,false,"unused"],11,2,2,2,2,11,[73,1,0,1,0],0,[73,0,0,2,0]],[0,23,40,0,0,2,0,1,1,[73,1,1,[41,0,25,true],1],1,1,[73,1,1,2,2],1,1,1,1,1,1,1,1,1,1,1,1,[73,1,0,1,0],0,0],[0,0,0,0,0,2,0,[73,1,0,1,0],[73,0,0,[84,1,0],0],0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,[73,1,0,1,0],0,[73,0,0,0,2]],[2,2,2,2,2,2,0,[73,1,0,1,0],0,0,0,23,[73,1,2,2,2],2,0,0,0,0,0,0,0,0,0,0,0,[73,1,0,1,0],0,0],[[73,2,2,1,3],0,0,0,0,0,[73,0,0,0,6],[73,1,1,1,0],[73,0,1,0,0],0,[73,0,0,1,0],0,2,0,0,0,0,0,0,0,0,0,0,0,0,[73,1,0,1,0],[73,0,2,0,0],[73,0,0,0,2]],[1,[73,0,0,8,0],0,0,0,0,0,0,0,[73,0,0,[84,1,0],0],0,0,2,0,0,2,0,0,0,2,0,0,0,0,0,[73,1,0,1,2],[73,0,0,0,2],[73,0,0,2,2]],[11,0,11,2,[73,2,2,0,0],[73,2,2,0,0],[73,2,2,0,0],[73,2,2,0,0],[73,2,2,0,0],[73,2,0,2,0],0,2,2,2,0,0,0,0,0,0,0,0,0,0,0,[73,1,2,1,2],[73,0,2,0,2],2],[[72,1000,1000,1000,1000],0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,[73,1,0,1,0],0,0],[2,11,2,11,2,11,2,11,0,[73,2,0,2,0],[49,10],26,[73,2,0,2,0],0,0,0,0,0,0,0,0,[73,0,2,0,2],0,0,0,[46,"cool you did it"],0,[41,0,24,true]],[[73,7,0,0,0],0,0,0,0,0,0,0,0,[73,2,0,[30,100],3],[73,7,[31,2,false,"unused"],0,0],[73,1,1,[33,2],7],[73,2,0,0,0],0,0,[73,0,2,0,2],0,0,0,0,0,[73,0,0,0,2],0,0,0,[73,1,0,1,0],0,[18,false,325,1,600,false,4000,20,1]]],[0,24,325,20,600,[null,null,false],false,false,false,4000,20,1,false,0,[]],"HARD MODE","Q"]

**Comment by TheTastyPi** [comment]
This should be fixed! Have fun :)

**Comment by ihateworkthatshard** [comment]
Thanks! 👍
